services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""   
      MYSQL_DATABASE: "proyecto_api_jwt"           
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  django-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=proyecto_api_jwt

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
