version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_api_task

  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: gunicorn mi_project_api.wsgi:application --bind 0.0.0.0:8000 --workers 3
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - network_api_task
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - network_api_task

volumes:
  mysql_data:
  static_volume:
  media_volume:


networks:
  network_api_task:
    driver: bridge
