services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_api_task

  django-app:
    build: .
    restart: always
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network_api_task

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django-app
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    environment:
      - proxy_no_cache=1
      - proxy_cache_bypass=1
    networks:
      - network_api_task

volumes:
  mysql_data:


networks:
  network_api_task:
    driver: bridge
